[phases.setup]
aptPkgs = ['ca-certificates']

[phases.build]
cmds = [
    # This force-adds the cert to the system-wide Java truststore during build
    'mkdir -p $JAVA_HOME/lib/security',
    'keytool -import -trustcacerts -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -alias niid-api -file niid.crt -noprompt',
    './mvnw clean install'
]

[variables]
NIXPACKS_JDK_VERSION = "21"